### ISSUE TITLE
path.resolve

### ISSUE THREAD

**Issue by crisz** [liuzzom/unisound#1]
path.resolve ha un funzionamento un po' strano, trovi una spiegazione qui:
https://nodejs.org/docs/latest/api/path.html#path_path_resolve_paths

In alcuni casi si risolve come un path assoluto e in altri casi come un path relativo. Se vuoi che il path sia sempre relativo potresti usare path.join()

**Comment by liuzzom** [comment]
ho provato ad utilizzare join ma ottengo degli errori. non capisco dove sbaglio

**Comment by crisz** [comment]
path.join non vuole separatori, niente slash nè backslash (anche perché sono platform-dependent). Quindi se vuoi referenziare file.js presente allo stesso livello, dovresti usare `path.join('file.js')` oppure `path.join(__dirname, 'file.js')`
