### ISSUE TITLE
express.static('./')

### ISSUE THREAD

**Issue by crisz** [liuzzom/unisound#2]
La suddetta linea di codice non fa altro che servire tutti i file del server, credenziali del db incluso. E' un gravissimo errore di sicurezza

**Comment by liuzzom** [comment]
non so come fare altrimenti per fornire i css. Hai qualche suggerimento?

**Comment by crisz** [comment]
Non senza cambiare la struttura

**Comment by liuzzom** [comment]
cambiata la struttura. Ora il metodo _app.use_ carica solo la cartella client, che non conterrà nulla relativo al db
