### ISSUE TITLE
node_modules non dovrebbe essere nella repo

### ISSUE THREAD

**Issue by crisz** [liuzzom/unisound#3]
`node_modules` contiene file platform-dependent e vanno installati in ogni macchina attraverso `npm install`. Dovresti utilizzare un file *.gitignore* per nodejs, ne trovi molti online e su github stesso

**Comment by liuzzom** [comment]
non li ho messi "volontariamente" ma si sono messi appena ho installato cose come express o body-parser. Come si fa per utilizzare i file .gitignore?

**Comment by crisz** [comment]
Aggiungi un file di nome *.gitignore* nel root, e dentro metti una riga con scritto:
node_modules
Dopo di che elimina i node_modules dalla repo

**Comment by liuzzom** [comment]
ho creato il file e rimosso la cartella, ma così non funziona. a Fede funziona ma perchè ha installato le cose globalmente

**Comment by crisz** [comment]
La cartella la devi rimuovere dalle repository su github, non dal progetto. La cartella deve esistere in locale ma non in remoto. Per ricreare la cartella, invoca `npm install`
