### ISSUE TITLE
client e server

### ISSUE THREAD

**Issue by crisz** [liuzzom/unisound#4]
E' ambiguo quali file appartengano al server e quali al client. Hai fatto questa distinzione solo per i file js, divisi in due cartelle.
Vi consiglio comunque di non dividere i file in base al tipo (js, html, css, ecc) ma in base alle funzionalità (canzoni, login, client, server)

**Comment by liuzzom** [comment]
stiamo modificando la struttura delle cartelle. Al prossimo push vedrai la nuova struttura, che spero sia più adeguata

**Comment by liuzzom** [comment]
struttura modificata
